<script setup lang="ts">
import { VCard, VAlert, VPagination, VSelect, VProgressLinear } from 'vuetify/components'
import {computed,onBeforeUnmount,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {adminApi,adminError} from './api'
const route=useRoute(),area=computed(()=>String(route.meta.adminArea||'dashboard'))
const titles:Record<string,string>={dashboard:'Обзор',content:'Контент сайта',services:'Услуги',directions:'Направления',reviews:'Отзывы',certificates:'Сертификаты',requests:'Заявки',media:'Медиатека',seo:'SEO',settings:'Настройки',audit:'Журнал действий'}
const rows=ref<any[]>([]),page=ref(1),total=ref(0),busy=ref(false),error=ref(''),notice=ref(''),dashboard=ref<any>(null),requestType=ref('bookings'),status=ref(''),requestDetail=ref<any>(null),note=ref(''),requestStatus=ref('new')
const statuses=[{title:'Новая',value:'new'},{title:'В работе',value:'in_progress'},{title:'Завершена',value:'completed'},{title:'Архив',value:'archived'}]
let poll:ReturnType<typeof setTimeout>|undefined
async function load(){busy.value=true;error.value='';clearTimeout(poll);try{
 if(area.value==='dashboard'){dashboard.value=(await adminApi.get('/dashboard')).data;if(dashboard.value.publication?.status==='running')poll=setTimeout(load,3000);return}
 if(area.value==='requests'){const {data}=await adminApi.get('/requests',{params:{type:requestType.value,status:status.value,page:page.value}});rows.value=data.items;total.value=data.total;return}
 if(area.value==='audit'){const {data}=await adminApi.get('/audit',{params:{page:page.value}});rows.value=data.items;total.value=data.total;return}
 }catch(e){error.value=adminError(e)}finally{busy.value=false}}
watch([area,requestType,status],()=>{page.value=1;load()},{immediate:true})
watch(page,load);onBeforeUnmount(()=>clearTimeout(poll))
async function publish(){busy.value=true;error.value='';try{await adminApi.post('/publish');notice.value='Публикация запущена. Статус появится в Обзоре.';if(area.value==='dashboard')await load()}catch(e){error.value=adminError(e)}finally{busy.value=false}}
function inspectRequest(r:any){requestDetail.value=r;note.value=r.internal_note||'';requestStatus.value=r.workflow_status||r.status}
async function saveRequest(){try{await adminApi.patch(`/requests/${requestType.value}/${requestDetail.value.id}`,{status:requestStatus.value,internal_note:note.value});requestDetail.value=null;await load()}catch(e){error.value=adminError(e)}}
const auditAction=(value:string)=>({login:'Вход',logout:'Выход',create:'Создание',update:'Изменение',archive:'Архивирование',restore:'Восстановление',publish:'Публикация',upload:'Загрузка','delete media':'Удаление изображения'} as Record<string,string>)[value]||value
const auditEntity=(value:string)=>({session:'Сессия',site:'Сайт',sections:'Секции',steps:'Шаги',services:'Услуги',options:'Варианты',reviews:'Отзывы',directions:'Направления',certificates:'Сертификаты',settings:'Настройки',pages:'SEO страниц',media:'Медиа',bookings:'Записи',contact_requests:'Вопросы'} as Record<string,string>)[value]||value
const price=(minor:number|null)=>minor==null?'—':new Intl.NumberFormat('ru',{style:'currency',currency:'EUR'}).format(minor/100)
</script>
<template>
 <h1>{{titles[area]}}</h1><v-alert v-if="error" type="error" class="mb-4">{{error}}</v-alert><v-alert v-if="notice" type="success" variant="tonal" closable class="mb-4" @click:close="notice=''">{{notice}}</v-alert><v-progress-linear v-if="busy" indeterminate class="mb-4"/>
 <template v-if="area==='dashboard'&&dashboard"><div class="admin-cards"><div v-for="(label,key) in {bookings:'Новые заявки',questions:'Новые вопросы',services:'Активные услуги',reviews:'Отзывы',certificates:'Сертификаты'}" :key="key" class="admin-card">{{label}}<strong>{{dashboard.counts[key]}}</strong></div></div>
 <div class="admin-actions"><v-btn to="/admin/services/new">Добавить услугу</v-btn><v-btn to="/admin/reviews/new">Добавить отзыв</v-btn><v-btn to="/admin/certificates/new">Добавить сертификат</v-btn><v-btn color="primary" :disabled="busy||dashboard.publication?.status==='running'" @click="publish">Опубликовать</v-btn></div>
 <p class="admin-muted">Последняя публикация: {{({running:'Выполняется',published:'Опубликовано',failed:'Ошибка'} as Record<string,string>)[dashboard.publication?.status]||'Ещё не выполнялась'}} {{dashboard.publication?.finished_at?new Date(dashboard.publication.finished_at).toLocaleString('ru'):''}}</p><p v-if="dashboard.publication?.error" role="alert">{{dashboard.publication.error}}</p>
 <h2 class="my-5">Последние заявки</h2><div class="admin-table"><table><tbody><tr v-for="r in dashboard.requests" :key="r.id"><td>{{r.name}}</td><td>{{r.service_title}}</td><td>{{price(r.total_price??r.price)}}</td><td><RouterLink to="/admin/requests">Открыть заявки</RouterLink></td></tr></tbody></table></div>
 <h2 class="my-5">Последние изменения</h2><div v-for="r in dashboard.audit" :key="r.id" class="admin-muted">{{new Date(r.created_at).toLocaleString('ru')}} · {{auditAction(r.action)}} · {{auditEntity(r.entity_type)}}</div></template>
 <template v-else-if="area==='requests'"><div class="admin-actions"><v-select v-model="requestType" label="Тип" :items="[{title:'Записи',value:'bookings'},{title:'Вопросы',value:'questions'}]"/><v-select v-model="status" label="Статус" :items="[{title:'Все',value:''},...statuses]"/></div><div class="admin-table"><table><thead><tr><th>Имя / контакты</th><th>Услуга</th><th>Стоимость</th><th>Статус</th><th>Дата</th><th></th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td>{{r.name}}<br>{{r.email}}<br>{{r.phone}}</td><td>{{r.service_title||'Вопрос'}}<br>{{r.language}}</td><td>{{price(r.total_price??r.price)}}</td><td>{{statuses.find(s=>s.value===(r.workflow_status||r.status))?.title}}</td><td>{{new Date(r.created_at).toLocaleString('ru')}}</td><td><v-btn variant="text" @click="inspectRequest(r)">Открыть</v-btn></td></tr></tbody></table></div></template>
 <template v-else-if="area==='audit'"><div class="admin-table"><table><thead><tr><th>Дата</th><th>Администратор</th><th>Действие</th><th>Объект</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td>{{new Date(r.created_at).toLocaleString('ru')}}</td><td>Администратор</td><td>{{auditAction(r.action)}}</td><td>{{auditEntity(r.entity_type)}}</td></tr></tbody></table></div></template>
 <v-pagination v-if="total>30&&area!=='content'" v-model="page" :length="Math.ceil(total/30)" class="mt-5"/>
 <v-dialog content-class="admin-dialog" :model-value="!!requestDetail" @update:model-value="v=>{if(!v)requestDetail=null}" max-width="800" scrollable><v-card class="pa-6" v-if="requestDetail"><h2>Заявка: {{requestDetail.name}}</h2><p class="my-3">{{requestDetail.name}} · {{requestDetail.email}} · {{requestDetail.phone}}</p><p style="white-space:pre-wrap;overflow-wrap:anywhere">{{requestDetail.message}}</p><dl class="my-5"><template v-for="(label,key) in {service_title:'Услуга',option_title:'Вариант',bonus_title:'Бонус',option_format:'Формат',language:'Язык',currency:'Валюта',preferred_date:'Историческая желаемая дата',consent_at:'Согласие получено',created_at:'Создано'}" :key="key"><dt>{{label}}</dt><dd>{{requestDetail[key]||'Не зафиксировано'}}</dd></template><dt>Основная цена / бонус / итог</dt><dd>{{price(requestDetail.price)}} / {{price(requestDetail.bonus_price)}} / {{price(requestDetail.total_price??requestDetail.price)}}</dd></dl><v-select v-model="requestStatus" label="Статус" :items="statuses"/><v-textarea v-model="note" label="Внутренняя заметка" maxlength="10000"/><div class="admin-actions"><v-btn color="primary" @click="saveRequest">Сохранить</v-btn><v-btn variant="text" @click="requestDetail=null">Закрыть</v-btn></div></v-card></v-dialog>
</template>
