import { legalDocuments, legalPages, technicalCookieSections, legalKey } from '../legal/content'
// Editorial labels and grouping belong to the admin UI, not the stored content.
export type Language = 'ru' | 'lv' | 'en'
export const languages: Language[] = ['ru', 'lv', 'en']
export interface ContentField {
  key: string; label: string; group: string; role?: string; rows?: number; help?: string; required?: boolean; readonly?: boolean
}
export interface SectionSpec {
  slug: string; title: string; description: string; source: string; fields: ContentField[]
  preview: 'hero'|'text-image'|'cta'|'text'|'steps'; image?: boolean; related?: {title:string; text:string; to:string}
}
const field = (key:string,label:string,group='Текст секции',role='body',rows=0,help=''):ContentField => ({key,label,group,role,rows,help,required:true})
const home=(key:string,label:string,group?:string,role?:string,rows?:number,help?:string)=>field('home.'+key,label,group,role,rows,help)
const about=(key:string,label:string,group?:string,role?:string,rows?:number)=>field('about.'+key,label,group,role,rows)
const accent='Эта строка отображается курсивом и акцентным цветом.'
export const pageLabels:Record<string,string>={home:'Главная',about:'Обо мне',services:'Услуги',reviews:'Отзывы',contacts:'Контакты',privacy:'Политика конфиденциальности',cookies:'Политика cookies',terms:'Условия оказания услуг',shared:'Шапка и подвал'}
export const publicPaths:Record<string,string>={home:'/',about:'/about',services:'/services',reviews:'/reviews',contacts:'/contacts',privacy:'/privacy',cookies:'/cookies',terms:'/terms',shared:'/'}
const cta:SectionSpec={slug:'final-cta',title:'Финальный CTA',description:'Приглашение к следующему шагу внизу страницы.',source:'global.cta',preview:'cta',fields:[
 field('finalCta.yourNextChapterStartsWithYou','Подпись над заголовком','Заголовок','eyebrow'),field('finalCta.whatIfNowIs','Заголовок — первая строка','Заголовок','title'),field('finalCta.theRightTimeTo','Заголовок — вторая строка','Заголовок','title2'),field('finalCta.chooseYourself','Акцентная часть','Заголовок','accent',0,accent),field('finalCta.youDontNeedAllTheAnswers','Описание — первая строка','Описание','body',2),field('finalCta.oneHonestConversationIsEnoughToBegin','Описание — вторая строка','Описание','body',2),field('finalCta.iWantToUnderstandMyself','Текст основной кнопки','Кнопки','primary'),field('finalCta.askAQuestionFirst','Текст дополнительной кнопки','Кнопки','secondary')
]}
export const contentPages:Record<string,SectionSpec[]>={
 home:[
 {slug:'hero',title:'Hero — первый экран',description:'Главное знакомство с экспертом: заголовок, фотография и приглашение.',source:'home.hero',preview:'hero',image:true,fields:[
 home('numerologySupportiveCoaching','Маленькая надпись над заголовком','Заголовок','eyebrow',0,'Отображается над главным заголовком.'),home('understandYourself','Заголовок — первая строка','Заголовок','title'),home('discoverYourStrength','Заголовок — вторая строка','Заголовок','title2'),home('findYourOwnPath','Акцентная строка','Заголовок','accent',0,accent),home('iHelpWomenListenToThemselvesSee','Описание','Описание','body',3),field('finalCta.iWantToUnderstandMyself','Текст основной кнопки','Кнопки','primary',0,'Этот текст также используется в общем финальном приглашении.'),home('askAQuestionFirst','Текст дополнительной кнопки','Кнопки','secondary'),home('lessFixingYourselfMoreBeingYourself','Короткая подпись под кнопками','Описание','caption'),home('heroExpertPortrait','Описание фотографии','Фотография','alt',2)]},
 {slug:'numerology',title:'Нумерология',description:'О подходе, возможностях разбора и внимании к себе.',source:'home.numerology',preview:'text-image',image:true,fields:[home('moreThanNumbers','Подпись над заголовком','Заголовок','eyebrow'),home('numerology','Заголовок — первая строка','Заголовок','title'),home('aWayToLookWithin','Заголовок — вторая строка','Заголовок','title2'),home('aLittleDeeper','Акцентная строка','Заголовок','accent',0,accent),home('yourDateOfBirthCanBeA','Первый абзац','Описание','body',4),home('wereNotLookingForAFixedDestiny','Второй абзац','Описание','body',4),home('aToolForSelfreflectionNotScientificAssessment','Нижняя фраза','Описание','note',3),home('exploreMySessions','Текст кнопки','Кнопки','primary'),home('thereIsAWholeWorldWithinYou','Подпись на фотографии','Фотография','caption'),home('aJournalForPersonalReflectionAPen','Описание фотографии','Фотография','alt',2)]},
 {slug:'directions',title:'С чем я работаю',description:'Заголовок блока направлений.',source:'home.directions',preview:'text',fields:[home('yourQuestionsAreYourOwn','Подпись над заголовком','Заголовок','eyebrow'),home('whatWeCan','Главный заголовок','Заголовок','title'),home('exploreTogether','Акцентная часть','Заголовок','accent',0,accent),home('allAreasOfFocus','Текст ссылки «Все направления»','Кнопки','primary')],related:{title:'Направления',text:'Карточки направлений управляются в разделе «Направления».',to:'/admin/directions'}},
 {slug:'how-it-works',title:'Как мы работаем',description:'Заголовок и последовательность шагов.',source:'home.process',preview:'steps',fields:[home('fromClarityToAction','Подпись над заголовком','Заголовок','eyebrow'),home('howWe','Главный заголовок','Заголовок','title'),home('workTogether','Акцентная часть','Заголовок','accent'),home('calmlyOneStepAtATime','Описание — первая строка','Описание','body',2),home('withAttentionToYou','Описание — вторая строка','Описание','body',2)]},
 {slug:'about',title:'Обо мне',description:'Короткое знакомство на главной странице.',source:'home.about-preview',preview:'text-image',image:true,fields:[home('letsMeet','Подпись над заголовком','Заголовок','eyebrow'),home('im','Заголовок — первая строка','Заголовок','title'),home('andIBelieveIn','Заголовок — вторая строка','Заголовок','title2'),home('yourStrength','Акцентная часть','Заголовок','accent'),home('iBringNumerologyAndCoachingQuestionsTogether','Первый абзац','Описание','body',4),home('iCareAboutCreatingASpaceWhere','Второй абзац','Описание','body',4),home('aLittleMoreAboutMe','Текст кнопки','Кнопки','primary'),home('heroExpertPortrait','Описание фотографии','Фотография','alt',2,'Общее описание для портретов эксперта на сайте.')]},
 {slug:'testimonials',title:'Отзывы',description:'Приглашение прочитать истории клиенток.',source:'home.testimonials',preview:'text',fields:[home('afterOurSessions','Подпись над заголовком','Заголовок','eyebrow'),home('wordsThat','Главный заголовок','Заголовок','title'),home('stayWithMe','Акцентная часть','Заголовок','accent'),field('reviews.all','Текст ссылки на все отзывы','Кнопки','primary')],related:{title:'Отзывы',text:'Тексты отзывов и выбор трёх избранных историй управляются в разделе «Отзывы».',to:'/admin/reviews'}},cta,
 {slug:'questions',title:'С какими мыслями приходят',description:'Вопросы, в которых посетительница может узнать себя.',source:'home.pain',preview:'text',fields:[home('letsGetToKnowYou','Подпись над заголовком','Заголовок','eyebrow'),home('perhapsYoureHere','Главный заголовок','Заголовок','title'),home('because','Акцентная часть','Заголовок','accent'),...['unsureWhereToGoNext','wantToDiscoverYourTrueStrengths','lookingForBalanceInRelationshipsAndMoney','feelTheresMoreWithinYou'].flatMap((key,i)=>[home(key,'Вопрос',`Карточка ${i+1}`,'body',2),home(['whenTheFamiliarNoLongerInspiresYou','andStopMeasuringYourselfAgainstOthers','withoutRepeatingTheSameOldPatterns','butDontYetKnowWhereToStart'][i]!,'Пояснение',`Карточка ${i+1}`,'body',2)]),home('theresNothingWrongWithYouLetsFind','Заключительная фраза','Описание','note',2)]},
 {slug:'values',title:'Полоса ценностей',description:'Четыре коротких принципа под первым экраном.',source:'home.supporting',preview:'text',fields:['withCareForYou','noPrewrittenScripts','groundedInYourself','atYourOwnPace'].map((key,i)=>home(key,`Принцип ${i+1}`,'Принципы','body'))},
 {slug:'services',title:'С чего начать',description:'Вводный текст перед форматами работы.',source:'home.services',preview:'text',fields:[home('spaceForYourNextChapter','Подпись над заголовком','Заголовок','eyebrow'),home('whereTo','Главный заголовок','Заголовок','title'),home('begin','Акцентная часть','Заголовок','accent'),home('chooseAFormatThatFeelsRight','Описание — первая строка','Описание','body',2),home('notSureWellDecideTogether','Описание — вторая строка','Описание','body',2)],related:{title:'Услуги',text:'Карточки, варианты и цены управляются в разделе «Услуги».',to:'/admin/services'}}
 ],
 about:[
 {slug:'intro',title:'Первый экран',description:'Заголовок страницы и фотография эксперта.',source:'about.intro',preview:'text-image',image:true,fields:[about('aboutMe','Подпись над заголовком','Заголовок','eyebrow'),about('hereToHelpYou','Главный заголовок','Заголовок','title'),about('hearYourself','Акцентная строка','Заголовок','accent'),about('imANumerologistAndCoach','Краткое представление','Описание','body',2),about('letsMeetForASession','Текст кнопки','Кнопки','primary'),home('heroExpertPortrait','Описание фотографии','Фотография','alt',2,'Общее описание для портретов эксперта на сайте.')]},
 {slug:'biography',title:'Обо мне / биография',description:'Личное знакомство и вопрос, с которого начинается работа.',source:'about.intro',preview:'text',fields:[about('myApproachBeginsWithASimpleQuestion','Рассказ о себе','Биография','body',6)]},
 {slug:'approach',title:'Мой подход',description:'Что происходит на встречах и как принимаются решения.',source:'about.intro',preview:'text',fields:[about('inOurSessionsWeExploreYourStrengths','Как проходят встречи','Подход','body',5),about('theDecisionsAreAlwaysYoursIDont','Важное о решениях клиентки','Подход','body',4)]},
 {slug:'principles',title:'Принципы',description:'Внимание, уважение и практика.',source:'about.intro',preview:'text',fields:[['01Attention','yourStoryComesFirst','weBeginWithYourQuestionAndThe'],['02Respect','withoutLabelsOrJudgment','youHaveTheRightToYourOwn'],['03Practice','turnInsightIntoAStepForward','weEndWithASpecificActionThat']].flatMap((keys,i)=>keys.map((key,n)=>about(key,['Номер и подпись','Заголовок','Описание'][n]!,`Принцип ${i+1}`,n===1?'title':'body',n===2?3:0)))},
 {slug:'education',title:'Образование',description:'Введение к профессиональным документам.',source:'about.certificates',preview:'text',fields:[field('certificates.eyebrow','Подпись над заголовком','Заголовок','eyebrow'),field('certificates.title','Главный заголовок','Заголовок','title'),field('certificates.intro','Описание','Описание','body',3)],related:{title:'Сертификаты',text:'Сами документы и их языковые версии управляются в разделе «Сертификаты».',to:'/admin/certificates'}},cta
 ],
 services:[{slug:'intro',title:'Заголовок и вводный текст',description:'Помогает выбрать подходящий формат работы.',source:'services.intro',preview:'text',fields:[field('services.individualSessions','Подпись над заголовком','Заголовок','eyebrow'),field('services.yourQuestion','Главный заголовок','Заголовок','title'),field('services.yourFirstStep','Акцентная строка','Заголовок','accent'),field('services.fromASingleConversationToOngoingSupport','Описание — первый абзац','Описание','body',3),field('services.chooseASpaceWhereYoudLikeTo','Описание — второй абзац','Описание','body',3)],related:{title:'Услуги',text:'Карточки и цены управляются в разделе «Услуги».',to:'/admin/services'}},{slug:'final-cta',title:'Финальное приглашение',description:'Помощь в выборе подходящего формата.',source:'services.intro',preview:'cta',fields:[field('services.notSure','Главный заголовок','Заголовок','title'),field('services.whatToChoose','Акцентная часть','Заголовок','accent'),field('services.tellMeALittleAboutYourSituation','Описание','Описание','body',3),field('services.askAQuestion','Текст кнопки','Кнопки','primary')]}],
 reviews:[{slug:'intro',title:'Введение к отзывам',description:'Заголовок и пояснение над историями.',source:'reviews.intro',preview:'text',fields:[field('reviews.eyebrow','Подпись над заголовком','Заголовок','eyebrow'),field('reviews.title','Главный заголовок','Заголовок','title'),field('reviews.intro','Вводный текст','Описание','body',3)],related:{title:'Отзывы',text:'Истории клиенток управляются в разделе «Отзывы».',to:'/admin/reviews'}},{slug:'final-cta',title:'Финальный CTA',description:'Приглашение после прочтения отзывов.',source:'reviews.intro',preview:'cta',fields:[field('reviews.ctaEyebrow','Подпись над заголовком','Заголовок','eyebrow'),field('reviews.ctaTitle','Главный заголовок','Заголовок','title'),field('reviews.ctaText','Описание','Описание','body',3),field('siteLayout.bookASession','Текст кнопки','Кнопки','primary',0,'Также используется в шапке сайта и других кнопках записи.')]}],
 contacts:[{slug:'intro',title:'Первый экран',description:'Приглашение к разговору.',source:'contacts.intro',preview:'text',fields:[field('contacts.letsKeepInTouch','Подпись над заголовком','Заголовок','eyebrow'),field('contacts.everyJourney','Заголовок — первая строка','Заголовок','title'),field('contacts.startsWith','Заголовок — вторая строка','Заголовок','title2'),field('contacts.aConversation','Акцентная строка','Заголовок','accent'),field('contacts.tellMeWhatMattersToYouRight','Описание — первая строка','Описание','body',3),field('contacts.illHelpYouFindYourNextStep','Описание — вторая строка','Описание','body',2)],related:{title:'Контактные данные',text:'Телефон, email и мессенджеры управляются в настройках.',to:'/admin/settings'}},{slug:'online',title:'Встречаемся онлайн',description:'Информация о формате встреч.',source:'contacts.intro',preview:'text',fields:[field('contacts.weMeetOnline','Заголовок','Заголовок','title'),field('contacts.fromAnywhereInTheWorldInA','Описание','Описание','body',3)]}],

 shared:[{slug:'footer',title:'Шапка и подвал',description:'Общие подписи и ссылки сайта.',source:'global.layout',preview:'text',fields:[field('siteLayout.closerToYourself','Заголовок подвала','Подвал','title'),field('siteLayout.closerToALifeYouChoose','Продолжение заголовка','Подвал','accent'),field('siteLayout.onlineInYourOwnSpace','Подпись о встречах','Подвал','body'),field('siteLayout.bookASession','Кнопка записи','Кнопки','primary')],related:{title:'Имя и контакты',text:'Имя специалиста и контактные данные меняются в настройках.',to:'/admin/settings'}}]
}
for(const page of legalPages) {
 contentPages[page]=[{slug:'document',title:'Заголовок и дата',description:'Дата публикации этой версии в формате ГГГГ-ММ-ДД.',source:`legal.${page}.document`,preview:'text',fields:[field(`legal.${page}.title`,'Название документа','Документ','title'),field(`legal.${page}.updated`,'Дата обновления','Документ','body')]},...legalDocuments.ru[page].sections.map((s,i)=>({slug:`section${i+1}`,title:s.title,description:page==='cookies'?'Юридический текст. Фактическая таблица хранения формируется из технической конфигурации сайта.':'Раздел документа. Пустая строка разделяет абзацы; строка с «- » создаёт пункт списка.',source:`legal.${page}.section${i+1}`,preview:'text' as const,fields:[field(legalKey(page,i,'title'),'Заголовок раздела','Раздел','title'),field(legalKey(page,i,'body'),'Текст раздела','Раздел','body',12,page==='terms'&&i===1?'Цена дополнительной встречи подставляется из каталога вместо {addonPrice}.':'Текст отображается безопасно, без HTML.')] }))]
}
for(const index of technicalCookieSections){const spec=contentPages.cookies?.find(s=>s.slug===`section${index+1}`);if(spec){spec.description='Технические сведения формируются из реализации сайта. Их изменение выполняется вместе с кодом, чтобы политика не описывала несуществующие технологии.';spec.fields.forEach(f=>{f.readonly=true})}}
export const clone=<T>(value:T):T=>JSON.parse(JSON.stringify(value))
export const localeRecord=(record:any,lang:Language)=>record.translations?.find((tr:any)=>tr.language===lang)
export const readField=(records:any[],key:string,lang:Language)=>records.map(r=>localeRecord(r,lang)?.fields?.[key]).find(v=>v!==undefined)||''
export const ownerOf=(records:any[],key:string)=>records.find(r=>r.translations?.some((tr:any)=>Object.hasOwn(tr.fields||{},key)))
export const friendly=(value:string,name='Елена Захарова')=>value.replaceAll('{name}',name)
export const sectionComplete=(spec:SectionSpec,records:any[],lang:Language)=>spec.fields.filter(f=>f.required).every(f=>String(readField(records,f.key,lang)).trim())
