<script setup lang="ts">
import {computed,ref,onMounted} from 'vue'
import {useRoute} from 'vue-router'
import {VAlert} from 'vuetify/components'
import {adminApi,adminError} from './api'
import {contentPages,pageLabels,readField,sectionComplete,languages,friendly} from './contentSchema'
const route=useRoute(),records=ref<any[]>([]),error=ref(''),loading=ref(true)
const page=computed(()=>String(route.params.page||'home')),specs=computed(()=>contentPages[page.value]||[])
onMounted(async()=>{try{records.value=(await adminApi.get('/entities/sections?limit=100')).data.items}catch(e){error.value=adminError(e)}finally{loading.value=false}})
</script>
<template><div class="admin-page-heading"><div><p class="admin-kicker">Контент сайта</p><h1>{{pageLabels[page]||'Страница не найдена'}}</h1><p class="admin-muted">Выберите блок, который хотите изменить. Тексты, фотография и предпросмотр — на одной странице.</p></div></div><nav class="admin-page-nav" aria-label="Страницы сайта"><RouterLink v-for="(label,key) in pageLabels" :key="key" :to="'/admin/content/'+key" :class="{active:page===key}">{{label}}</RouterLink></nav><v-alert v-if="error" type="error">{{error}}</v-alert><p v-if="loading" role="status">Загружаем контент…</p><div v-else class="content-card-grid"><article v-for="spec in specs" :key="spec.slug" class="content-card"><div class="card-topline"><span class="admin-kicker">{{spec.title}}</span><span v-if="records.find(r=>r.section_key===spec.source)?.is_active===false" class="admin-badge">Скрыт</span></div><h2>{{friendly(spec.fields.filter(f=>['title','title2','accent'].includes(f.role||'')).map(f=>readField(records,f.key,'ru')).join(' '))||spec.title}}</h2><p class="admin-muted">{{spec.description}}</p><div class="translation-badges"><span v-for="lang in languages" :key="lang" :class="{missing:!sectionComplete(spec,records,lang)}">{{lang.toUpperCase()}} <v-icon :icon="sectionComplete(spec,records,lang)?'mdi-check-circle-outline':'mdi-alert-circle-outline'" size="16"/><span class="sr-only">{{sectionComplete(spec,records,lang)?'заполнено':'есть пропуски'}}</span></span></div><p v-if="spec.related" class="admin-related-note">{{spec.related.text}} <RouterLink :to="spec.related.to">Перейти <v-icon icon="mdi-arrow-top-right" size="18"/></RouterLink></p><RouterLink :to="`/admin/content/${page}/${spec.slug}`" class="admin-edit-link">Редактировать <v-icon icon="mdi-arrow-top-right" size="18"/></RouterLink></article></div></template>
