<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {VAlert,VPagination} from 'vuetify/components'
import {adminApi,adminError} from './api'
import {entityNames,entityFields,recordTitle,priceLabel,valueOf} from './entitySchema'
import {languages,pageLabels} from './contentSchema'
const route=useRoute(),kind=computed(()=>route.meta.adminArea==='seo'?'pages':String(route.meta.adminArea)),rows=ref<any[]>([]),options=ref<any[]>([]),page=ref(1),total=ref(0),loading=ref(false),error=ref(''),confirmRecord=ref<any>(null)
let request=0
async function load(){const id=++request;loading.value=true;error.value='';try{const {data}=await adminApi.get('/entities/'+kind.value,{params:{page:page.value,limit:12}});if(id!==request)return;rows.value=data.items;total.value=data.total;if(kind.value==='services'){const all:any[]=[];let p=1;for(;;){const result=(await adminApi.get('/entities/options',{params:{page:p,limit:100}})).data;all.push(...result.items);if(all.length>=result.total)break;p++}if(id===request)options.value=all}}catch(e){error.value=adminError(e)}finally{if(id===request)loading.value=false}}
watch(kind,()=>{page.value=1;load()},{immediate:true});watch(page,load)
const routeBase=computed(()=>kind.value==='pages'?'seo':kind.value)
function complete(row:any,lang:string){const required=(entityFields[kind.value]||[]).filter(f=>f.required);return required.every(f=>valueOf(row,f.key,lang,kind.value).trim())}
async function toggle(){try{const row=confirmRecord.value;await adminApi.put('/entities/'+kind.value+'/'+row.id,{...row,is_active:!row.is_active});confirmRecord.value=null;await load()}catch(e){error.value=adminError(e)}}
const description:Record<string,string>={services:'Форматы работы, изображения, основные варианты и бонусы.',directions:'Темы, с которыми можно прийти. Цены берутся из связанных услуг.',reviews:'Реальные истории клиенток. Для главной выбираются три избранных отзыва.',certificates:'Профессиональные документы и изображения на разных языках.',pages:'Как страницы выглядят в поисковой выдаче. Адреса и языковые ссылки формируются автоматически.'}
</script>
<template><div class="admin-page-heading"><div><p class="admin-kicker">Управление контентом</p><h1>{{entityNames[kind]}}</h1><p class="admin-muted">{{description[kind]}}</p></div><v-btn v-if="kind!=='pages'" :to="`/admin/${kind}/new`" color="primary">{{({services:'Добавить услугу',directions:'Добавить направление',reviews:'Добавить отзыв',certificates:'Добавить сертификат'} as Record<string,string>)[kind]}}</v-btn></div><v-alert v-if="error" type="error">{{error}}</v-alert><p v-if="loading" role="status">Загружаем материалы…</p><p v-else-if="!rows.length" class="admin-empty">Здесь пока нет материалов. Добавьте первый.</p><div class="entity-card-grid"><article v-for="row in rows" :key="row.id" class="entity-card"><img v-if="row.image||row.assets?.[0]?.media?.storage_path" :src="row.image||row.assets[0].media.storage_path" alt="" loading="lazy" class="entity-card-image" :class="{'certificate-image':kind==='certificates'}"/><div class="entity-card-body"><div class="card-topline"><span class="admin-badge" :class="{inactive:row.is_active===false}">{{kind==='pages'?'Страница':row.is_active===false?'В архиве':'На сайте'}}</span><span v-if="row.is_featured" class="admin-badge">Избранный</span></div><h2>{{kind==='pages'?pageLabels[row.key]:recordTitle(row,kind)}}</h2><template v-if="kind==='services'"><p class="entity-price">От {{priceLabel(row.price)}}</p><p class="admin-muted">Вариантов: {{options.filter(o=>o.service_id===row.id).length}}</p></template><p class="entity-excerpt">{{kind==='reviews'?valueOf(row,'short_text','ru',kind)||valueOf(row,'full_text','ru',kind):kind==='pages'?valueOf(row,'meta_description','ru',kind):valueOf(row,'short_description','ru',kind)||valueOf(row,'description','ru',kind)}}</p><div class="translation-badges"><span v-for="lang in languages" :key="lang" :class="{missing:!complete(row,lang)}">{{lang.toUpperCase()}} <v-icon :icon="complete(row,lang)?'mdi-check-circle-outline':'mdi-alert-circle-outline'" size="16"/></span></div><div class="entity-card-actions"><RouterLink :to="`/admin/${routeBase}/${row.id}`" class="admin-edit-link">Редактировать <v-icon icon="mdi-arrow-top-right" size="18"/></RouterLink><v-btn v-if="kind!=='pages'" variant="text" size="small" @click="confirmRecord=row">{{row.is_active?'Архивировать':'Восстановить'}}</v-btn></div></div></article></div><v-pagination v-if="total>12" v-model="page" :length="Math.ceil(total/12)" :total-visible="4"/>
 <v-dialog :model-value="!!confirmRecord" @update:model-value="confirmRecord=null" max-width="440"><div class="admin-small-dialog" v-if="confirmRecord"><h2>{{confirmRecord.is_active?'Скрыть материал с сайта?':'Вернуть материал на сайт?'}}</h2><p>{{recordTitle(confirmRecord,kind)}}</p><p class="admin-muted">Существующие заявки и их цены сохранятся.</p><div class="admin-actions"><v-btn variant="text" @click="confirmRecord=null">Отмена</v-btn><v-btn color="primary" @click="toggle">{{confirmRecord.is_active?'Архивировать':'Восстановить'}}</v-btn></div></div></v-dialog></template>
