import type {ContentField} from './contentSchema'
const f=(key:string,label:string,group='Основная информация',role='body',rows=0,help='',required=false):ContentField=>({key,label,group,role,rows,help,required})
export const entityNames:Record<string,string>={services:'Услуги',options:'Варианты услуги',directions:'Направления',reviews:'Отзывы',certificates:'Сертификаты',pages:'SEO страниц',settings:'Настройки'}
export const entityFields:Record<string,ContentField[]>={
 services:[f('title','Название','Основная информация','title',0,'',true),f('short_description','Краткое описание','Основная информация','body',3),f('description','Полное описание','Основная информация','body',6),f('duration','Длительность','Основная информация','caption'),f('alt','Описание изображения','Изображение','alt',2)],
 options:[f('title','Название варианта','Основная информация','title',0,'',true),f('format','Что входит в этот вариант','Основная информация','body',3)],
 directions:[f('eyebrow','Подпись над заголовком','Основная информация','eyebrow'),f('title','Название','Основная информация','title',0,'',true),f('short_description','Краткое описание для карточки','Основная информация','body',3),f('lead','Вводный текст','Описание','body',4),f('context','Основной текст','Описание','body',5),f('format_note','Пояснение к выбору формата','Описание','note',3),f('insights','Что можно увидеть','Дополнительные тексты','body',5,'Каждый пункт пишите с новой строки.'),f('questions','С какими вопросами можно прийти','Дополнительные тексты','body',5,'Каждый вопрос пишите с новой строки.'),f('process','Как проходит разбор','Дополнительные тексты','body',5),f('alt','Описание изображения','Изображение','alt',2),f('seo_title','SEO-заголовок','Поисковая выдача','title'),f('seo_description','Описание для поисковиков','Поисковая выдача','body',3)],
 reviews:[f('short_text','Короткая версия для главной','Текст отзыва','body',3,'Короткая версия используется на главной.'),f('full_text','Полная версия для страницы отзывов','Текст отзыва','body',7,'Полная версия используется на странице «Отзывы».',true)],
 certificates:[f('title','Название сертификата','Основная информация','title',0,'',true),f('description','Описание обучения','Основная информация','body',3),f('alt','Описание документа','Основная информация','alt',2)],
 pages:[f('title','Название страницы','Поисковая выдача','caption',0,'Название для списка страниц в административной панели.',true),f('meta_title','SEO-заголовок','Поисковая выдача','title',0,'Обычно в выдаче видно около 50–60 символов. Это рекомендация, не ограничение.',true),f('meta_description','Описание для поисковиков','Поисковая выдача','body',3,'Кратко опишите содержание страницы. Ориентир — 140–160 символов.',true)],
 settings:[f('professional_title','Профессиональная подпись','Имя и подпись','body',0,'Например: Нумеролог · Женский коуч.')]
}
export const flatKinds=['services','options','settings']
export function valueOf(record:any,key:string,lang:string,kind:string):string{return flatKinds.includes(kind)?record[key+'_'+lang]||'':record.translations?.find((tr:any)=>tr.language===lang)?.[key]||''}
export function setValue(record:any,key:string,lang:string,kind:string,value:string){if(flatKinds.includes(kind))record[key+'_'+lang]=value;else{record.translations||=[];let tr=record.translations.find((t:any)=>t.language===lang);if(!tr){tr={language:lang};record.translations.push(tr)}tr[key]=value}}
export const recordTitle=(record:any,kind:string)=>kind==='settings'?'Контакты и имя специалиста':record.title_ru||record.translations?.find((t:any)=>t.language==='ru')?.title||record.author_display_name||(kind==='reviews'?'Отзыв клиентки':'Новый материал')
export const priceLabel=(minor:number|null|undefined)=>minor==null?'Цена не указана':new Intl.NumberFormat('ru',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(minor/100)
