<script setup lang="ts">
import {ref,watch,onMounted} from 'vue'
import {VSelect,VPagination,VAlert} from 'vuetify/components'
import {adminApi,adminError} from './api'
import {contentPages} from './contentSchema'
const props=defineProps<{picker?:boolean}>()
const emit=defineEmits<{select:[asset:any];close:[]}>()
const items=ref<any[]>([]),selected=ref<any>(null),search=ref(''),query=ref(''),category=ref('all'),page=ref(1),total=ref(0),loading=ref(false),uploading=ref(false),error=ref(''),fileInput=ref<HTMLInputElement>(),deleteOpen=ref(false)
let request=0
async function load(){const id=++request;loading.value=true;error.value='';try{const {data}=await adminApi.get('/media',{params:{q:query.value,category:category.value,page:page.value,limit:12}});if(id!==request)return;items.value=data.items;total.value=data.total}catch(e){if(id===request)error.value=adminError(e)}finally{if(id===request)loading.value=false}}
watch([page,category],load);onMounted(load)
function find(){if(page.value!==1){query.value=search.value;page.value=1}else{query.value=search.value;load()}}
async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;error.value='';if(file.size>10*1024*1024){error.value='Выберите изображение размером до 10 МБ.';return}uploading.value=true;try{const form=new FormData();form.append('file',file);const {data}=await adminApi.post('/media',form,{timeout:120000});selected.value={asset:data,usage_count:0,uses:[]};category.value='all';page.value=1;query.value='';search.value='';await load()}catch(e){error.value=adminError(e)}finally{uploading.value=false;if(fileInput.value)fileInput.value.value=''}}
async function remove(){if(!selected.value)return;try{await adminApi.delete('/media/'+selected.value.asset.id);selected.value=null;deleteOpen.value=false;await load()}catch(e){error.value=adminError(e)}}
const thumbnail=(asset:any)=>asset.variants?.['640']||asset.variants?.['800']||asset.storage_path
function location(use:any){if(use.kind==='sections'){for(const [page,specs] of Object.entries(contentPages)){const spec=specs.find(s=>s.source===use.key);if(spec)return {title:spec.title,to:`/admin/content/${page}/${spec.slug}`}}}return {title:use.title||'Связанный материал',to:`/admin/${use.kind}/${use.id}`}}
</script>
<template><div class="media-library"><div class="admin-page-heading"><div><h1 v-if="!picker">Медиатека</h1><h2 v-else>Выберите изображение</h2><p class="admin-muted">Фотографии и сертификаты. JPEG, PNG, WebP или AVIF, до 10 МБ.</p></div><v-btn v-if="picker" icon="mdi-close" variant="text" aria-label="Закрыть медиатеку" @click="$emit('close')"/></div><v-alert v-if="error" type="error" class="mb-4">{{error}}</v-alert>
 <div class="media-toolbar"><form @submit.prevent="find" class="media-search"><v-text-field v-model="search" label="Найти изображение" density="comfortable" hide-details clearable @click:clear="search='';find()"/><v-btn type="submit" variant="tonal" aria-label="Найти">Найти</v-btn></form><v-select v-model="category" label="Тип изображения" :items="[{title:'Все',value:'all'},{title:'Фото',value:'photos'},{title:'Сертификаты',value:'certificates'}]" density="comfortable" hide-details @update:model-value="page=1"/><v-btn color="primary" :loading="uploading" @click="fileInput?.click()">Загрузить изображение</v-btn><input ref="fileInput" type="file" class="admin-file-input" aria-label="Загрузить изображение" accept="image/jpeg,image/png,image/webp,image/avif" @change="upload"/></div>
 <div class="media-layout"><div><p v-if="loading" role="status" class="admin-muted">Загружаем изображения…</p><p v-else-if="!items.length" class="admin-empty">Изображений не найдено. Измените поиск или загрузите новое.</p><div class="media-grid"><button v-for="item in items" :key="item.asset.id" type="button" class="media-tile" :class="{selected:selected?.asset.id===item.asset.id}" :aria-pressed="selected?.asset.id===item.asset.id" :aria-label="'Выбрать изображение '+item.asset.original_filename" @click="selected=item"><img :src="thumbnail(item.asset)" alt="" loading="lazy" width="240" height="180"/><span>{{item.asset.width}} × {{item.asset.height}}</span><small>{{item.asset.original_filename}}</small></button></div><v-pagination v-if="total>12" v-model="page" :length="Math.ceil(total/12)" :total-visible="4"/></div>
 <aside class="media-detail"><template v-if="selected"><img :src="selected.asset.storage_path" alt="Предпросмотр выбранного изображения"/><h3>Выбранное изображение</h3><dl><dt>Размер файла</dt><dd>{{(selected.asset.size/1024).toFixed(0)}} КБ</dd><dt>Размер изображения</dt><dd>{{selected.asset.width}} × {{selected.asset.height}} px</dd></dl><h4>Где используется</h4><p class="admin-muted">{{selected.usage_count?'Используется в '+selected.usage_count+' местах.':'Пока не используется на сайте.'}}</p><RouterLink v-for="(use,i) in selected.uses" :key="i" :to="location(use).to" class="admin-inline-link">{{location(use).title}}</RouterLink><div class="admin-actions"><v-btn v-if="picker" color="primary" @click="emit('select',selected.asset)">Выбрать изображение</v-btn><v-btn v-else variant="outlined" @click="fileInput?.click()">Загрузить замену</v-btn><v-btn variant="text" :disabled="selected.usage_count>0||!selected.asset.storage_path.startsWith('/media/')" @click="deleteOpen=true">Удалить</v-btn></div><p class="admin-muted" v-if="selected.usage_count">Чтобы заменить изображение, откройте нужный блок по ссылке выше. Используемый файл защищён от удаления.</p></template><p v-else class="admin-muted">Выберите изображение, чтобы увидеть его размер и место использования.</p></aside></div>
 <v-dialog v-model="deleteOpen" max-width="440"><div class="admin-small-dialog"><h2>Удалить изображение?</h2><p>Файл не используется на сайте. Восстановить его после удаления нельзя.</p><div class="admin-actions"><v-btn variant="text" @click="deleteOpen=false">Отмена</v-btn><v-btn color="primary" @click="remove">Удалить</v-btn></div></div></v-dialog>
 </div></template>
