<script setup lang="ts">
import type { ContentField } from './contentSchema'
import { friendly } from './contentSchema'
const props=withDefaults(defineProps<{fields:ContentField[];values:Record<string,string>;image?:string;type?:string;name?:string;steps?:any[]}>(),{type:'text',name:'Елена Захарова'})
const values=(role:string)=>props.fields.filter(f=>f.role===role).map(f=>friendly(props.values[f.key]||'',props.name)).filter(Boolean)
</script>
<template><aside class="editor-preview"><div class="editor-preview-label"><v-icon icon="mdi-eye-outline" size="18"/>Предпросмотр секции<span>Текущий язык</span></div><div class="section-draft" :class="['preview-'+type,{'has-photo':image}]" aria-hidden="true" inert>
 <img v-if="image" :src="image" alt="" class="section-draft-photo"/>
 <div class="section-draft-copy"><small v-for="text in values('eyebrow')" :key="text">{{text}}</small><h2><template v-for="text in [...values('title'),...values('title2')]" :key="text">{{text}}<br></template><em v-for="text in values('accent')" :key="text">{{text}}</em></h2><p v-for="(text,i) in values('body')" :key="i">{{text}}</p><div v-if="values('primary').length||values('secondary').length" class="draft-buttons"><span v-for="text in values('primary')" :key="text" class="draft-button">{{text}} <ArrowIcon/></span><span v-for="text in values('secondary')" :key="text" class="draft-link">{{text}} <ArrowIcon/></span></div><p v-for="text in [...values('note'),...values('caption')]" :key="text" class="draft-note">{{text}}</p><div v-if="steps?.length" class="draft-steps"><div v-for="step in steps" :key="step.id"><small>{{step.label}}</small><h3>{{step.title}}</h3><p>{{step.description}}</p></div></div></div>
 </div><p class="admin-muted preview-explanation">Предпросмотр обновляется без сохранения. На сайте секция подстраивается под ширину экрана.</p></aside></template>
<style scoped>
.editor-preview{position:sticky;top:24px;align-self:start;min-width:0}.editor-preview-label{display:flex;align-items:center;gap:8px;margin-bottom:16px;font-size:13px;color:#665c53}.editor-preview-label span{margin-left:auto;font-size:11px}.section-draft{background:#faf7f2;border:1px solid var(--line);border-radius:12px;overflow:hidden;color:var(--ink);font-family:'Manrope',Arial,sans-serif;position:relative;min-height:300px;overflow-wrap:anywhere}.section-draft-copy{padding:32px;position:relative}.section-draft h2{font:500 34px/1.08 var(--serif);letter-spacing:-.6px;margin:14px 0 24px}.section-draft h2 em{color:#9e7652;font-weight:400}.section-draft small{font-size:9px;letter-spacing:2px;text-transform:uppercase}.section-draft p{font-size:12px;line-height:1.8;margin:16px 0;white-space:pre-line}.section-draft-photo{width:100%;height:220px;object-fit:cover}.preview-hero .section-draft-photo{position:absolute;inset:0;height:100%;object-position:75% center}.preview-hero .section-draft-copy{background:linear-gradient(90deg,#faf7f2 0%,#faf7f2ee 35%,#faf7f220 85%);min-height:390px;padding-right:35%}.preview-hero h2{font-size:31px}.draft-buttons{display:flex;flex-wrap:wrap;gap:16px;align-items:center;margin:20px 0}.draft-button{background:var(--brown);color:white;padding:12px 16px;font-size:10px;display:inline-flex;align-items:center;gap:10px}.draft-link{font-size:10px;display:inline-flex;gap:8px;align-items:center}.draft-button svg,.draft-link svg{width:18px;height:18px}.section-draft .draft-note{font-size:10px;color:var(--muted)}.preview-cta{background:#59402f;color:#fffaf5;text-align:center}.preview-cta h2 em{color:#e1c2a5}.preview-cta .draft-buttons{justify-content:center}.preview-cta .draft-button{background:#fffaf5;color:var(--brown)}.draft-steps{display:grid;gap:20px}.draft-steps h3{font:500 26px var(--serif);margin:8px 0}.preview-explanation{margin-top:12px}@media(max-width:1199px){.editor-preview{position:static}.section-draft{max-width:700px}.preview-hero .section-draft-copy{padding-right:40%}}@media(max-width:600px){.section-draft-copy{padding:24px}.preview-hero .section-draft-copy{padding:24px 34% 24px 24px}.preview-hero h2{font-size:28px}}
</style>
