<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {VAlert,VSelect,VSwitch,VSnackbar} from 'vuetify/components'
import {adminApi,adminError} from './api'
import {clone,contentPages,pageLabels,publicPaths,readField,ownerOf,localeRecord,languages,sectionComplete,type Language} from './contentSchema'
import {languagePath} from '../i18n/urls'
import {useUnsaved} from './useUnsaved'
import FriendlyField from './FriendlyField.vue'
import LanguageTabs from './LanguageTabs.vue'
import SectionPreview from './SectionPreview.vue'
import ImageField from './ImageField.vue'
import SaveBar from './SaveBar.vue'
const route=useRoute(),records=ref<any[]>([]),original=ref<any[]>([]),steps=ref<any[]>([]),originalSteps=ref<any[]>([]),schema=ref<any[]>([]),language=ref<Language>('ru'),name=ref('Елена Захарова'),busy=ref(false),loading=ref(true),error=ref(''),saved=ref(false),errors=ref<Record<string,string>>({})
const page=computed(()=>String(route.params.page)),spec=computed(()=>contentPages[page.value]?.find(s=>s.slug===route.params.section))
const section=computed(()=>records.value.find(r=>r.section_key===spec.value?.source))
const definition=computed(()=>schema.value.find(s=>s.section_key===spec.value?.source))
const dirty=computed(()=>JSON.stringify(records.value)!==JSON.stringify(original.value)||JSON.stringify(steps.value)!==JSON.stringify(originalSteps.value))
useUnsaved(dirty)
let request=0
async function load(){const id=++request;loading.value=true;error.value='';try{const [a,b,c]=await Promise.all([adminApi.get('/entities/sections?limit=100'),adminApi.get('/schema'),adminApi.get('/entities/settings')]);if(id!==request)return;records.value=a.data.items;original.value=clone(records.value);schema.value=b.data;name.value=c.data.items[0]?.expert_name||name.value;steps.value=spec.value?.preview==='steps'?(await adminApi.get('/entities/steps?limit=100')).data.items:[];for(const step of steps.value)for(const lang of languages)stepTranslation(step,lang);originalSteps.value=clone(steps.value);errors.value={}}catch(e){error.value=adminError(e)}finally{if(id===request)loading.value=false}}
watch(()=>route.path,load,{immediate:true})
const groups=computed(()=>[...new Set(spec.value?.fields.map(f=>f.group))])
const completeness=computed(()=>Object.fromEntries(languages.map(lang=>[lang,!!spec.value&&sectionComplete(spec.value,records.value,lang)&&steps.value.every(s=>localeRecord(s,lang)?.title?.trim())])))
const previewValues=computed(()=>Object.fromEntries((spec.value?.fields||[]).map(f=>[f.key,readField(records.value,f.key,language.value)])))
function setField(key:string,value:string){const record=ownerOf(records.value,key);if(!record)return;let tr=localeRecord(record,language.value);if(!tr){tr={language:language.value,fields:{}};record.translations.push(tr)}tr.fields[key]=value;delete errors.value[key]}
function stepTranslation(step:any,lang=language.value){let tr=localeRecord(step,lang);if(!tr){tr={language:lang,label:'',title:'',description:''};step.translations.push(tr)}return tr}
function addStep(){steps.value.push({page_section_id:section.value.id,sort_order:steps.value.length,icon_key:'arrow',translations:languages.map(language=>({language,label:'',title:'',description:''}))})}
function cancel(){if(confirm('Отменить несохранённые изменения?')){records.value=clone(original.value);steps.value=clone(originalSteps.value);errors.value={};error.value=''}}
async function save(){if(busy.value||!spec.value)return;errors.value={};for(const f of spec.value.fields)if(f.required&&!readField(records.value,f.key,'ru').trim())errors.value[f.key]=`${f.label}: заполните текст RU.`;for(const [i,step] of steps.value.entries())if(!localeRecord(step,'ru')?.title?.trim())errors.value['step-'+i]='Заголовок RU обязателен.';if(Object.keys(errors.value).length){language.value='ru';return}busy.value=true;error.value='';try{
 for(const record of records.value){const previous=original.value.find(r=>r.id===record.id);if(JSON.stringify(record)===JSON.stringify(previous))continue;await adminApi.put('/entities/sections/'+record.id,record);const fresh=(await adminApi.get('/entities/sections/'+record.id)).data;Object.assign(record,fresh);original.value[original.value.findIndex(r=>r.id===record.id)]=clone(fresh)}
 for(let i=0;i<steps.value.length;i++){const step=steps.value[i],old=originalSteps.value.find(s=>s.id===step.id);if(old&&JSON.stringify(step)===JSON.stringify(old))continue;const {data}=await adminApi.request({method:step.id?'put':'post',url:'/entities/steps'+(step.id?'/'+step.id:''),data:step});const fresh=(await adminApi.get('/entities/steps/'+data.id)).data;steps.value[i]=fresh;const index=originalSteps.value.findIndex(s=>s.id===fresh.id);if(index<0)originalSteps.value.push(clone(fresh));else originalSteps.value[index]=clone(fresh)}
 saved.value=true
 }catch(e){error.value=adminError(e)}finally{busy.value=false}}
const destinations=[{title:'Запись на встречу',value:'booking'},{title:'Задать вопрос',value:'question'},{title:'Услуги',value:'services'},{title:'Отзывы',value:'reviews'},{title:'Обо мне',value:'about'}]
</script>
<template><p v-if="loading" role="status">Загружаем редактор…</p><template v-else-if="spec&&section"><RouterLink :to="'/admin/content/'+page" class="admin-back"><v-icon icon="mdi-arrow-left" size="18"/>{{pageLabels[page]}}</RouterLink><div class="admin-page-heading"><div><p class="admin-kicker">Редактор секции</p><h1>{{spec.title}}</h1><p class="admin-muted">{{spec.description}}</p></div><a :href="languagePath(publicPaths[page]||'/',language)" target="_blank" rel="noopener" class="admin-view-link">Посмотреть на сайте <v-icon icon="mdi-open-in-new" size="16"/></a></div><v-alert v-if="error&&!dirty" type="error">{{error}}</v-alert>
 <SaveBar :dirty="dirty" :busy="busy" :error="error" @save="save" @cancel="cancel"/><div class="admin-editor-layout"><div class="editor-fields"><LanguageTabs v-model="language" :complete="completeness"/>
 <div v-if="spec.related" class="admin-related"><p>{{spec.related.text}}</p><RouterLink :to="spec.related.to">Перейти в раздел «{{spec.related.title}}» <v-icon icon="mdi-arrow-top-right" size="18"/></RouterLink></div>
 <section v-for="group in groups" :key="group" class="editor-group"><h2>{{group}}</h2><ImageField v-if="group==='Фотография'&&spec.image" v-model="section.settings.image"/><FriendlyField v-for="field in spec.fields.filter(f=>f.group===group)" :key="field.key" :model-value="readField(records,field.key,language)" @update:model-value="setField(field.key,$event)" :label="field.label" :rows="field.rows" :help="field.help" :error="language==='ru'?errors[field.key]:''" :expert-name="name" :template="readField(original,field.key,language).includes('{name}')" :counter="['title','title2','accent'].includes(field.role||'')" :required="language==='ru'&&field.required"/>
 <template v-if="group==='Кнопки'"><v-select v-if="definition?.settings.primary_destination" v-model="section.settings.primary_destination" label="Куда ведёт основная кнопка" :items="destinations" variant="outlined"/><v-select v-if="definition?.settings.secondary_destination" v-model="section.settings.secondary_destination" label="Куда ведёт дополнительная кнопка" :items="destinations" variant="outlined"/></template></section>
 <section v-if="spec.preview==='steps'" class="editor-group"><h2>Шаги работы</h2><details v-for="(step,i) in steps" :key="step.id||'new'+i" class="editor-disclosure" :open="i===0"><summary>Шаг {{i+1}} · {{localeRecord(step,language)?.title||'Без названия'}}</summary><div><FriendlyField v-model="stepTranslation(step).label" label="Номер или подпись"/><FriendlyField v-model="stepTranslation(step).title" label="Заголовок шага" :error="errors['step-'+i]"/><FriendlyField v-model="stepTranslation(step).description" label="Описание шага" :rows="3"/><v-select v-model="step.icon_key" label="Иконка" :items="[{title:'Стрелка',value:'arrow'},{title:'Внимание',value:'eye'},{title:'Идея',value:'lightbulb'},{title:'Цель',value:'target'}]"/><v-text-field v-model.number="step.sort_order" label="Порядок шага" type="number"/></div></details><v-btn variant="outlined" @click="addStep">Добавить шаг</v-btn></section>
 <details v-if="contentPages[page]?.find(s=>s.source===spec?.source)?.slug===spec.slug" class="editor-group editor-disclosure"><summary>Показ на сайте и порядок</summary><div><v-switch v-model="section.is_active" label="Показывать блок на сайте" :disabled="definition?.critical" color="primary" hide-details/><p class="admin-muted" v-if="definition?.critical">Это обязательная часть страницы. Её нельзя случайно скрыть.</p><v-text-field v-if="page==='home'&&!definition?.critical" v-model.number="section.sort_order" label="Порядок на странице" type="number" class="mt-4" hint="Меньшее число — выше на странице." persistent-hint/><p v-if="spec.source==='global.cta'" class="admin-muted">Этот блок общий для нескольких страниц. Изменения появятся во всех его версиях.</p></div></details>
 </div><SectionPreview :type="spec.preview" :fields="spec.fields" :values="previewValues" :image="spec.image?section.settings.image:undefined" :name="name" :steps="steps.map(s=>({...localeRecord(s,language),id:s.id}))"/></div><v-snackbar v-model="saved" color="success" :timeout="3500">Изменения сохранены</v-snackbar></template><v-alert v-else type="warning">Секция не найдена. <RouterLink to="/admin/content">Вернуться к контенту</RouterLink></v-alert></template>
