<script setup lang="ts">
import { useI18n } from 'vue-i18n'
const { t } = useI18n()

import { computed, onMounted, ref } from 'vue'
import ServiceCards from '../components/ServiceCards.vue'
import HeroSection from '../components/HeroSection.vue'
import FinalCta from '../components/FinalCta.vue'
import { getTestimonials, errorKey } from '../services/api'
import { getLocalizedField } from '../i18n/localized'
import type { Testimonial } from '../types'
import { useReveal } from '../composables/useReveal'
useReveal()
const testimonials=ref<Testimonial[]>([]),reviewError=ref(''),reviewLoading=ref(true),reviewTrack=ref<HTMLElement|null>(null)
async function loadReviews(){reviewLoading.value=true;reviewError.value='';try{testimonials.value=await getTestimonials()}catch(e){reviewError.value=errorKey(e)}finally{reviewLoading.value=false}}
onMounted(loadReviews)
const pains=computed(()=>[{icon:'mdi-compass-outline',text:t('home.unsureWhereToGoNext'),note:t('home.whenTheFamiliarNoLongerInspiresYou')},{icon:'mdi-white-balance-sunny',text:t('home.wantToDiscoverYourTrueStrengths'),note:t('home.andStopMeasuringYourselfAgainstOthers')},{icon:'mdi-heart-outline',text:t('home.lookingForBalanceInRelationshipsAndMoney'),note:t('home.withoutRepeatingTheSameOldPatterns')},{icon:'mdi-sprout-outline',text:t('home.feelTheresMoreWithinYou'),note:t('home.butDontYetKnowWhereToStart')}])
const directions=computed(()=>[{title:t('home.youAndYourPotential'),text:t('home.yourCharacterTalentsAndTheStrengthsAlready'),icon:'mdi-white-balance-sunny',slug:'personal-matrix',image:'/images/expert-placeholder.webp',class:'portrait-card'},{title:t('home.purposeAndMoney'),text:t('home.meaningfulWorkFulfilmentAndYourRelationshipWith'),icon:'mdi-compass-outline',slug:'growth-point',image:'/images/journal-placeholder.webp',class:'journal-card'},{title:t('home.relationships'),text:t('home.closenessPersonalBoundariesAndUnderstandingEachOther'),icon:'mdi-heart-outline',slug:'growth-point',image:'/images/relationships-placeholder.webp',class:'relationship-card'},{title:t('home.yourChildsMatrix'),text:t('home.understandYourChildsIndividualityAndHowTo'),icon:'mdi-sprout-outline',slug:'growth-point',image:'/images/child-placeholder.webp',class:'child-card'}])
const steps=computed(()=>[{title:t('home.seeYourselfClearly'),text:t('home.weStartWithYourQuestionAndExplore')},{title:t('home.understandWhatsHappening'),text:t('home.weNoticeFamiliarPatternsAndDiscoverWhat')},{title:t('home.takeTheNextStep'),text:t('home.weTurnUnderstandingIntoSmallPracticalSteps')}])
</script>
<template>
<HeroSection />
<div class="values-strip"><span>{{ t('home.withCareForYou') }}</span><span aria-hidden="true">✧</span><span>{{ t('home.noPrewrittenScripts') }}</span><span aria-hidden="true">✧</span><span>{{ t('home.groundedInYourself') }}</span><span aria-hidden="true">✧</span><span>{{ t('home.atYourOwnPace') }}</span></div>
<section class="section container pain-section" data-reveal><div class="section-heading centered"><span class="eyebrow">{{ t('home.letsGetToKnowYou') }}</span><h2>{{ t('home.perhapsYoureHere') }} <em>{{ t('home.because') }}</em></h2></div><div class="pain-grid"><article v-for="p in pains" :key="p.text"><v-icon :icon="p.icon" size="34"/><h3>{{p.text}}</h3><p>{{p.note}}</p></article></div><p class="handwritten">{{ t('home.theresNothingWrongWithYouLetsFind') }} <span>♡</span></p></section>
<section class="numerology-section" data-reveal><div class="container split-section"><div class="journal-visual"><img src="/images/journal-placeholder.webp" :alt="t('home.aJournalForPersonalReflectionAPen')" loading="lazy" width="1536" height="1024"/><span class="image-caption">{{ t('home.thereIsAWholeWorldWithinYou') }}</span></div><div class="section-copy"><span class="eyebrow">{{ t('home.moreThanNumbers') }}</span><h2>{{ t('home.numerology') }}<br>{{ t('home.aWayToLookWithin') }}<br><em>{{ t('home.aLittleDeeper') }}</em></h2><p>{{ t('home.yourDateOfBirthCanBeA') }}</p><p>{{ t('home.wereNotLookingForAFixedDestiny') }}</p><router-link to="/services" class="text-link">{{ t('home.exploreMySessions') }} <span>↗</span></router-link><small class="method-note">{{ t('home.aToolForSelfreflectionNotScientificAssessment') }}</small></div></div></section>
<section id="directions" class="section container" data-reveal><div class="section-heading heading-row"><div><span class="eyebrow">{{ t('home.yourQuestionsAreYourOwn') }}</span><h2>{{ t('home.whatWeCan') }} <em>{{ t('home.exploreTogether') }}</em></h2></div><router-link class="text-link" to="/services">{{ t('home.allAreasOfFocus') }} <span>↗</span></router-link></div><div class="direction-grid"><router-link v-for="d in directions" :key="d.title" :to="`/services/${d.slug}`" class="direction-card"><div class="direction-photo" :class="d.class"><img :src="d.image" :alt="d.title" loading="lazy" width="400" height="300"/><span class="round-icon"><v-icon :icon="d.icon" size="25"/></span></div><div class="direction-content"><h3>{{d.title}} <span>↗</span></h3><p>{{d.text}}</p></div></router-link></div></section>
<section class="process-section" data-reveal><div class="container process-layout"><div><span class="eyebrow">{{ t('home.fromClarityToAction') }}</span><h2>{{ t('home.howWe') }}<br><em>{{ t('home.workTogether') }}</em></h2><p>{{ t('home.calmlyOneStepAtATime') }}<br>{{ t('home.withAttentionToYou') }}</p></div><div class="steps"><article v-for="(s,i) in steps" :key="s.title"><div class="step-number">0{{i+1}}<span aria-hidden="true">⟶</span></div><h3>{{s.title}}</h3><p>{{s.text}}</p></article></div></div></section>
<section id="services" class="section container" data-reveal><div class="section-heading heading-row"><div><span class="eyebrow">{{ t('home.spaceForYourNextChapter') }}</span><h2>{{ t('home.whereTo') }} <em>{{ t('home.begin') }}</em></h2></div><p class="section-intro">{{ t('home.chooseAFormatThatFeelsRight') }}<br>{{ t('home.notSureWellDecideTogether') }}</p></div><ServiceCards/></section>
<section class="about-preview" data-reveal><div class="container about-layout"><div class="about-photo"><img src="/images/hero/hero-main.webp" :alt="t('home.heroExpertPortrait', { name: t('siteLayout.expertName') })" loading="lazy" width="1672" height="941"/></div><div class="section-copy"><span class="eyebrow">{{ t('home.letsMeet') }}</span><h2>{{ t('home.im') }}<br>{{ t('home.andIBelieveIn') }} <em>{{ t('home.yourStrength') }}</em></h2><p>{{ t('home.iBringNumerologyAndCoachingQuestionsTogether') }}</p><p>{{ t('home.iCareAboutCreatingASpaceWhere') }}</p><router-link class="text-link" to="/about">{{ t('home.aLittleMoreAboutMe') }} <span>↗</span></router-link></div></div></section>
<section id="testimonials" class="section container" data-reveal><div class="section-heading heading-row"><div><span class="eyebrow">{{ t('home.afterOurSessions') }}</span><h2>{{ t('home.wordsThat') }} <em>{{ t('home.stayWithMe') }}</em></h2></div><div v-if="testimonials.length > 3" class="review-controls"><v-btn icon="mdi-arrow-left" variant="outlined" :aria-label="t('home.previousTestimonial')" @click="reviewTrack?.scrollBy({left:-340,behavior:'smooth'})"/><v-btn icon="mdi-arrow-right" variant="outlined" :aria-label="t('home.nextTestimonial')" @click="reviewTrack?.scrollBy({left:340,behavior:'smooth'})"/></div></div><p class="demo-review-label">{{ t('home.exampleTestimonialsForTheLayoutRealStories') }}</p><p v-if="reviewLoading" role="status">{{ t('home.loadingTestimonials') }}</p><p v-else-if="reviewError" role="alert">{{t(reviewError)}} <v-btn variant="text" @click="loadReviews">{{ t('requestForm.tryAgain') }}</v-btn></p><p v-else-if="!testimonials.length">{{ t('home.clientStoriesWillAppearHereSoon') }}</p><div v-else ref="reviewTrack" class="testimonial-grid" tabindex="0" :aria-label="t('home.testimonialsScrollToReadMore')"><article v-for="review in testimonials" :key="review.id" class="testimonial"><span class="quote-mark" aria-hidden="true">“</span><p>{{getLocalizedField(review, 'text')}}</p><div class="review-author"><span class="avatar-letter">{{getLocalizedField(review, 'client_name')[0]}}</span><span>{{getLocalizedField(review, 'client_name')}}</span><span class="rating" :aria-label="t('accessibility.rating', {rating: review.rating})">{{'★'.repeat(review.rating)}}</span></div></article></div></section>
<FinalCta/>
</template>
