<script setup lang="ts">
import { useI18n } from 'vue-i18n'
const { t, locale } = useI18n()
import { content, translated, sectionImage, ctaDestination } from '../stores/content'
import CmsSections from '../components/CmsSections'

import { findDirection } from '../data/directions'
import { computed } from 'vue'
import ServiceCards from '../components/ServiceCards.vue'
import HeroSection from '../components/HeroSection.vue'
import FinalCta from '../components/FinalCta.vue'
import { useReveal } from '../composables/useReveal'
useReveal()
const featuredReviews=computed(()=>content.reviews.filter(r=>r.is_featured).sort((a,b)=>(a.home_sort_order??a.sort_order)-(b.home_sort_order??b.sort_order)).slice(0,3))
const testimonialKeys = ['first', 'second', 'third'] as const
const pains=computed(()=>[{icon:'mdi-compass-outline',text:t('home.unsureWhereToGoNext'),note:t('home.whenTheFamiliarNoLongerInspiresYou')},{icon:'mdi-white-balance-sunny',text:t('home.wantToDiscoverYourTrueStrengths'),note:t('home.andStopMeasuringYourselfAgainstOthers')},{icon:'mdi-heart-outline',text:t('home.lookingForBalanceInRelationshipsAndMoney'),note:t('home.withoutRepeatingTheSameOldPatterns')},{icon:'mdi-sprout-outline',text:t('home.feelTheresMoreWithinYou'),note:t('home.butDontYetKnowWhereToStart')}])
const directions=computed(()=>content.ready ? content.directions.map(d=>({title:translated(d,'title',locale.value),text:translated(d,'short_description',locale.value),slug:d.slug,image:d.image,icon:({potential:'mdi-white-balance-sunny','purpose-money':'mdi-compass-outline',relationships:'mdi-heart-outline','child-matrix':'mdi-sprout-outline'} as Record<string,string>)[d.slug]||'mdi-compass-outline',class:({potential:'portrait-card','purpose-money':'journal-card',relationships:'relationship-card','child-matrix':'child-card'} as Record<string,string>)[d.slug]||''})) : [{title:t('home.youAndYourPotential'),text:t('home.yourCharacterTalentsAndTheStrengthsAlready'),icon:'mdi-white-balance-sunny',slug:'potential',image:'/images/optimized/expert-1672.webp',class:'portrait-card'},{title:t('home.purposeAndMoney'),text:t('home.meaningfulWorkFulfilmentAndYourRelationshipWith'),icon:'mdi-compass-outline',slug:'purpose-money',image:'/images/journal-placeholder.webp',class:'journal-card'},{title:t('home.relationships'),text:t('home.closenessPersonalBoundariesAndUnderstandingEachOther'),icon:'mdi-heart-outline',slug:'relationships',image:'/images/relationships-placeholder.webp',class:'relationship-card'},{title:t('home.yourChildsMatrix'),text:t('home.understandYourChildsIndividualityAndHowTo'),icon:'mdi-sprout-outline',slug:'child-matrix',image:'/images/child-placeholder.webp',class:'child-card'}])
const steps=computed(()=>content.ready? content.steps.map(s=>({title:translated(s,'title',locale.value),text:translated(s,'description',locale.value),label:translated(s,'label',locale.value),icon:s.icon_key})) : [{title:t('home.seeYourselfClearly'),text:t('home.weStartWithYourQuestionAndExplore')},{title:t('home.understandWhatsHappening'),text:t('home.weNoticeFamiliarPatternsAndDiscoverWhat')},{title:t('home.takeTheNextStep'),text:t('home.weTurnUnderstandingIntoSmallPracticalSteps')}])
</script>
<template>
<CmsSections>
<HeroSection data-cms-section="home.hero" />
<div class="values-strip" data-cms-section="home.supporting"><span>{{ t('home.withCareForYou') }}</span><span aria-hidden="true">✧</span><span>{{ t('home.noPrewrittenScripts') }}</span><span aria-hidden="true">✧</span><span>{{ t('home.groundedInYourself') }}</span><span aria-hidden="true">✧</span><span>{{ t('home.atYourOwnPace') }}</span></div>
<section data-cms-section="home.pain" class="section container pain-section" data-reveal><div class="section-heading centered"><span class="eyebrow">{{ t('home.letsGetToKnowYou') }}</span><h2>{{ t('home.perhapsYoureHere') }} <em>{{ t('home.because') }}</em></h2></div><div class="pain-grid"><article v-for="p in pains" :key="p.text"><v-icon :icon="p.icon" size="34"/><h3>{{p.text}}</h3><p>{{p.note}}</p></article></div><p class="handwritten">{{ t('home.theresNothingWrongWithYouLetsFind') }} <span>♡</span></p></section>
<section data-cms-section="home.numerology" class="numerology-section" data-reveal><div class="container split-section"><div class="journal-visual"><img :src="sectionImage('home.numerology', '/images/journal-placeholder.webp')" :alt="t('home.aJournalForPersonalReflectionAPen')" loading="lazy" decoding="async" width="1536" height="1024"/><span class="image-caption">{{ t('home.thereIsAWholeWorldWithinYou') }}</span></div><div class="section-copy"><span class="eyebrow">{{ t('home.moreThanNumbers') }}</span><h2>{{ t('home.numerology') }}<br>{{ t('home.aWayToLookWithin') }}<br><em>{{ t('home.aLittleDeeper') }}</em></h2><p>{{ t('home.yourDateOfBirthCanBeA') }}</p><p>{{ t('home.wereNotLookingForAFixedDestiny') }}</p><LocaleLink :to="ctaDestination('home.numerology','primary_destination','services')" class="text-link">{{ t('home.exploreMySessions') }} <span><ArrowIcon /></span></LocaleLink><small class="method-note">{{ t('home.aToolForSelfreflectionNotScientificAssessment') }}</small></div></div></section>
<section data-cms-section="home.directions" id="directions" class="section container" data-reveal><div class="section-heading heading-row"><div><span class="eyebrow">{{ t('home.yourQuestionsAreYourOwn') }}</span><h2>{{ t('home.whatWeCan') }} <em>{{ t('home.exploreTogether') }}</em></h2></div><LocaleLink class="text-link" to="/services">{{ t('home.allAreasOfFocus') }} <span><ArrowIcon /></span></LocaleLink></div><div class="direction-grid"><LocaleLink v-for="d in directions" :key="d.title" :to="`/directions/${d.slug}`" class="direction-card"><div class="direction-photo" :class="d.class"><img :src="findDirection(d.slug)?.image || d.image" :alt="d.title" loading="lazy" decoding="async" width="400" height="300"/><span class="round-icon"><v-icon :icon="d.icon" size="25"/></span></div><div class="direction-content"><h3>{{d.title}} <span><ArrowIcon /></span></h3><p>{{d.text}}</p></div></LocaleLink></div></section>
<section data-cms-section="home.process" class="process-section" data-reveal><div class="container process-layout"><div><span class="eyebrow">{{ t('home.fromClarityToAction') }}</span><h2>{{ t('home.howWe') }}<br> <em>{{ t('home.workTogether') }}</em></h2><p>{{ t('home.calmlyOneStepAtATime') }}<br>{{ t('home.withAttentionToYou') }}</p></div><div class="steps"><article v-for="(s,i) in steps" :key="s.title"><div class="step-number">{{ 'label' in s ? s.label : '0'+(i+1) }}<span aria-hidden="true"><ArrowIcon v-if="!('icon' in s) || s.icon==='arrow'" direction="right" /><v-icon v-else :icon="({eye:'mdi-eye-outline',lightbulb:'mdi-lightbulb-outline',target:'mdi-target'} as Record<string,string>)[s.icon]" /></span></div><h3>{{s.title}}</h3><p>{{s.text}}</p></article></div></div></section>
<section data-cms-section="home.services" id="services" class="section container" data-reveal><div class="section-heading heading-row"><div><span class="eyebrow">{{ t('home.spaceForYourNextChapter') }}</span><h2>{{ t('home.whereTo') }} <em>{{ t('home.begin') }}</em></h2></div><p class="section-intro">{{ t('home.chooseAFormatThatFeelsRight') }}<br>{{ t('home.notSureWellDecideTogether') }}</p></div><ServiceCards/></section>
<section data-cms-section="home.about-preview" class="about-preview" data-reveal><div class="container about-layout"><div class="about-photo"><img :src="sectionImage('home.about-preview', '/images/optimized/expert-1672.webp')" :alt="t('home.heroExpertPortrait', { name: t('siteLayout.expertName') })" loading="lazy" decoding="async" width="1672" height="941"/></div><div class="section-copy"><span class="eyebrow">{{ t('home.letsMeet') }}</span><h2>{{ t('home.im') }}<br>{{ t('home.andIBelieveIn') }} <em>{{ t('home.yourStrength') }}</em></h2><p>{{ t('home.iBringNumerologyAndCoachingQuestionsTogether') }}</p><p>{{ t('home.iCareAboutCreatingASpaceWhere') }}</p><LocaleLink class="text-link" :to="ctaDestination('home.about-preview','primary_destination','about')">{{ t('home.aLittleMoreAboutMe') }} <span><ArrowIcon /></span></LocaleLink></div></div></section>
<section data-cms-section="home.testimonials" id="testimonials" class="section container" data-reveal><div class="section-heading heading-row"><div><span class="eyebrow">{{ t('home.afterOurSessions') }}</span><h2>{{ t('home.wordsThat') }} <em>{{ t('home.stayWithMe') }}</em></h2></div></div><div class="testimonial-grid" tabindex="0" :aria-label="t('home.testimonialsScrollToReadMore')"><article v-for="(review, i) in (content.ready ? featuredReviews : testimonialKeys)" :key="i" class="testimonial"><span class="quote-mark" aria-hidden="true">“</span><p>{{ typeof review === 'string' ? t(`home.testimonials.${review}`) : translated(review,'short_text',locale) }}</p><div class="review-author"><span class="avatar-letter" aria-hidden="true">{{ t('home.testimonials.author')[0] }}</span><span>{{ typeof review === 'string' ? t('home.testimonials.author') : review.author_display_name || t('home.testimonials.author') }}</span></div></article></div><div class="all-reviews-link"><LocaleLink class="text-link" to="/reviews">{{ t('reviews.all') }} <ArrowIcon /></LocaleLink></div></section>
<FinalCta data-cms-section="global.cta"/>
</CmsSections>
</template>

<style scoped>
.testimonial { display:flex; flex-direction:column; }
.testimonial > p { flex:1; }
.all-reviews-link { margin-top:28px; text-align:center; }
@media(max-width:600px) {
 .testimonial-grid { align-items:flex-start; }
 .testimonial > p { min-height:0; }
}
</style>
